### ISSUE TITLE
Error on startup of first example

### ISSUE THREAD

**Issue by witcradg** [gluon-framework/gluon#64]
510  git clone https://github.com/gluon-framework/examples.git
  511  ll
  512  cd examples
  513  ll
  514  cd gluworld
  515  npm install
  516  node .
  517  h
dean@pop-os ~/.../examples/gluworld (main) $ node .
[Gluon] starting browser...
file:///home/dean/projects/gatsby/LIBRARY/gluon/examples/gluworld/node_modules/@gluon-framework/gluon/src/index.js:198
  const [ browserPath, browserName ] = await findBrowserPath(forceBrowser, forceEngine);
                                       ^

TypeError: (intermediate value) is not iterable
    at startBrowser (file:///home/dean/projects/gatsby/LIBRARY/gluon/examples/gluworld/node_modules/@gluon-framework/gluon/src/index.js:198:40)
    at async Module.open (file:///home/dean/projects/gatsby/LIBRARY/gluon/examples/gluworld/node_modules/@gluon-framework/gluon/src/index.js:255:19)
    at async file:///home/dean/projects/gatsby/LIBRARY/gluon/examples/gluworld/index.js:17:3

Node.js v18.12.1
dean@pop-os ~/.../examples/gluworld (main) $ 

Happy to help any way I can.

**Comment by CanadaHonk** [comment]
What browsers do you have installed on your system?

**Comment by witcradg** [comment]
chrome and firefox

**Comment by witcradg** [comment]
I'm using !Pop_os so it's a flatpak install

**Comment by witcradg** [comment]
I can run it from the command line with this command:
flatpak run com.google.Chrome

**Comment by witcradg** [comment]
of course, I can also use
/usr/bin/flatpak run com.google.Chrome
